### PR TITLE
Convert the README to markdown

### PR DESCRIPTION
**Pull request by jhalterman**
Markdown renders nicely on Github.

### CODE REVIEW

**Comment by jhalterman** [comment]
@lincolnthomas @gholms I wasn't sure if a JIRA was needed for something like this, but do you think this is a good idea?

**Comment by lincolnthomas** [comment]
@jhalterman I think leaving the README as plain text is fine, which is historically done. If you clone or download the code somehow and then look at the README file in your directory tree, you won't have the nice markdown rendering. Plain text ensures it's readable anywhere. We can put all the nicely formatted docs we want into the user docs, Wikis, PDFs, etc.

I think PRs should be for actual code changes to review, not for ideas/to-do's like this which should be a JIRA issue. But if we decide not to change the README format, no JIRA issue needed.

Regardless, I think you can close this PR, since there's nothing to review. We can always make a new PR if something is changed.

**Comment by jhalterman** [comment]
@lincolnthomas I would agree, but have a look at the commit. The diff barely changes anything. Mostly the extension just needs to be changed since it's already formatted in a markdown'ish style.

**Comment by lincolnthomas** [comment]
Ha! I didn't realize the commit changed anything except the filename! I thought this was a general question and you wanted to change a lot later with headers / fonts / lists / whatever. I see now, my bad.

Yes, go ahead and commit it, no JIRA required IMHO. Thanks!

**Comment by jhalterman** [comment]
Cool - not sure how long automergic to master takes, but it's in maint-4.4:

https://github.com/eucalyptus/eucalyptus/tree/maint-4.4

**Pull request closed without merging**
